import OpenAI from "openai";
import { inngest } from "./client";
import { db } from "@/db";
import { prSummaries, codeReviews, triageResults } from "@/db/schema";
import {
  getInstallationOctokit,
  getPRFiles,
  postPRComment,
  postPRReview,
  applyIssueLabels,
  postIssueComment,
} from "@/lib/github";

function getOpenAI(): OpenAI {
  return new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

// ── PR Summary ────────────────────────────────────────────────────────────────

export const prSummary = inngest.createFunction(
  { id: "pr-summary", name: "PR Summary", triggers: [{ event: "dispatch/pr-summary" }] },
  async ({ event, step }) => {
    const payload = event.data as {
      action: string;
      pull_request: {
        number: number;
        title: string;
        body: string | null;
        user: { login: string };
        head: { ref: string };
        base: { ref: string };
        additions: number;
        deletions: number;
        changed_files: number;
      };
      repository: { full_name: string; name: string; owner: { login: string } };
      installation?: { id: number };
    };

    if (!["opened", "synchronize", "reopened"].includes(payload.action)) {
      return { skipped: true, reason: `action=${payload.action}` };
    }

    const pr = payload.pull_request;
    const repo = payload.repository;
    const [owner, repoName] = repo.full_name.split("/");

    const diff = await step.run("fetch-diff", async () => {
      const octokit = payload.installation?.id
        ? await getInstallationOctokit(payload.installation.id)
        : null;
      if (!octokit) return "";
      return getPRFiles(octokit, owner, repoName, pr.number);
    });

    const summaryText = await step.run("generate-summary", async () => {
      const openai = getOpenAI();

      const prompt = `You are a senior engineer doing a high-level PR review. Summarize the following pull request clearly and concisely.

Repository: ${repo.full_name}
PR #${pr.number}: ${pr.title}
Author: ${pr.user.login}
Branch: ${pr.head.ref} → ${pr.base.ref}
Stats: +${pr.additions} / -${pr.deletions} across ${pr.changed_files} files

Description:
${pr.body || "(no description provided)"}

${diff ? `Changed files (up to 30):\n${diff}` : ""}

Write a summary (3–5 sentences) covering:
1. What this PR does and why
2. The main technical changes
3. Any notable risk areas or things to watch out for

Be direct and technical. No bullet points — write in flowing prose.`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [{ role: "user", content: prompt }],
        max_tokens: 600,
        temperature: 0.3,
      });

      return response.choices[0].message.content ?? "(no summary generated)";
    });

    await step.run("save-to-db", async () => {
      await db.insert(prSummaries).values({
        repoFullName: repo.full_name,
        prNumber: pr.number,
        summaryText,
      });
    });

    await step.run("post-comment", async () => {
      const octokit = payload.installation?.id
        ? await getInstallationOctokit(payload.installation.id)
        : null;
      if (!octokit) return;

      const body = `## Dispatch AI Summary\n\n${summaryText}\n\n---\n*Generated by [Dispatch](https://github.com/apps/dispatch)*`;
      await postPRComment(octokit, owner, repoName, pr.number, body);
    });

    return { success: true, repoFullName: repo.full_name, prNumber: pr.number };
  }
);

// ── Code Review ───────────────────────────────────────────────────────────────

export const codeReview = inngest.createFunction(
  { id: "code-review", name: "Code Review", triggers: [{ event: "dispatch/code-review" }] },
  async ({ event, step }) => {
    const payload = event.data as {
      action: string;
      pull_request: {
        number: number;
        title: string;
        body: string | null;
        user: { login: string };
        head: { ref: string };
        base: { ref: string };
        additions: number;
        deletions: number;
        changed_files: number;
      };
      repository: { full_name: string; name: string; owner: { login: string } };
      installation?: { id: number };
    };

    if (payload.action !== "review_requested") {
      return { skipped: true, reason: `action=${payload.action}` };
    }

    const pr = payload.pull_request;
    const repo = payload.repository;
    const [owner, repoName] = repo.full_name.split("/");

    const diff = await step.run("fetch-diff", async () => {
      const octokit = payload.installation?.id
        ? await getInstallationOctokit(payload.installation.id)
        : null;
      if (!octokit) return "";
      return getPRFiles(octokit, owner, repoName, pr.number);
    });

    const reviewText = await step.run("generate-review", async () => {
      const openai = getOpenAI();

      const prompt = `You are an experienced senior engineer performing a thorough code review. Review the following pull request and provide constructive, actionable feedback.

Repository: ${repo.full_name}
PR #${pr.number}: ${pr.title}
Author: ${pr.user.login}
Branch: ${pr.head.ref} → ${pr.base.ref}
Stats: +${pr.additions} / -${pr.deletions} across ${pr.changed_files} files

Description:
${pr.body || "(no description provided)"}

${diff ? `Changes:\n${diff}` : "(diff unavailable — reviewing from description only)"}

Provide a structured review covering:
1. **Overall Assessment** — Is this PR ready to merge? What is the quality level?
2. **Issues Found** — Specific problems (bugs, security issues, performance concerns). For each: describe the issue, file/location if identifiable, and how to fix it.
3. **Suggestions** — Non-blocking improvements (naming, readability, test coverage, edge cases).
4. **Positives** — What is done well.

Be specific and technical.`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [{ role: "user", content: prompt }],
        max_tokens: 1200,
        temperature: 0.3,
      });

      return response.choices[0].message.content ?? "(no review generated)";
    });

    const reviewId = await step.run("post-review", async () => {
      const octokit = payload.installation?.id
        ? await getInstallationOctokit(payload.installation.id)
        : null;
      if (!octokit) return "no-octokit";

      const body = `## Dispatch AI Code Review\n\n${reviewText}\n\n---\n*Generated by [Dispatch](https://github.com/apps/dispatch)*`;
      return postPRReview(octokit, owner, repoName, pr.number, body, "COMMENT");
    });

    await step.run("save-to-db", async () => {
      await db.insert(codeReviews).values({
        repoFullName: repo.full_name,
        prNumber: pr.number,
        reviewId: String(reviewId),
      });
    });

    return { success: true, repoFullName: repo.full_name, prNumber: pr.number };
  }
);

// ── Ticket Triage ─────────────────────────────────────────────────────────────

export const ticketTriage = inngest.createFunction(
  { id: "ticket-triage", name: "Ticket Triage", triggers: [{ event: "dispatch/ticket-triage" }] },
  async ({ event, step }) => {
    const payload = event.data as {
      action: string;
      issue: {
        number: number;
        title: string;
        body: string | null;
        user: { login: string };
        labels: Array<{ name: string }>;
      };
      repository: { full_name: string; name: string; owner: { login: string } };
      installation?: { id: number };
    };

    if (payload.action !== "opened") {
      return { skipped: true, reason: `action=${payload.action}` };
    }

    const issue = payload.issue;
    const repo = payload.repository;
    const [owner, repoName] = repo.full_name.split("/");

    const triage = await step.run("generate-triage", async () => {
      const openai = getOpenAI();

      const prompt = `You are a project manager triaging GitHub issues. Analyze this issue and return a JSON response.

Repository: ${repo.full_name}
Issue #${issue.number}: ${issue.title}
Author: ${issue.user.login}
Existing labels: ${issue.labels.map((l) => l.name).join(", ") || "none"}

Body:
${issue.body || "(no body)"}

Respond with ONLY valid JSON in this exact format:
{
  "labels": ["label1", "label2"],
  "priority": "critical|high|medium|low",
  "category": "bug|enhancement|question|documentation|other",
  "summary": "One sentence explaining what this issue is about.",
  "action": "One sentence recommending the immediate next action."
}

Label guidelines:
- Choose 1-3 labels from: bug, enhancement, question, documentation, good first issue, help wanted, duplicate, wontfix, invalid
- Always include the category as a label
- Priority: critical=data loss/security/blocker, high=important feature/significant bug, medium=normal, low=nice to have/minor`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [{ role: "user", content: prompt }],
        max_tokens: 300,
        temperature: 0.1,
        response_format: { type: "json_object" },
      });

      const raw = response.choices[0].message.content ?? "{}";
      try {
        return JSON.parse(raw) as {
          labels: string[];
          priority: string;
          category: string;
          summary: string;
          action: string;
        };
      } catch {
        return {
          labels: ["needs-triage"],
          priority: "medium",
          category: "other",
          summary: "Unable to parse triage result.",
          action: "Manual triage required.",
        };
      }
    });

    await step.run("apply-labels", async () => {
      const octokit = payload.installation?.id
        ? await getInstallationOctokit(payload.installation.id)
        : null;
      if (!octokit) return;

      const allLabels = [...triage.labels, `priority:${triage.priority}`];
      await applyIssueLabels(octokit, owner, repoName, issue.number, allLabels);
    });

    await step.run("post-triage-comment", async () => {
      const octokit = payload.installation?.id
        ? await getInstallationOctokit(payload.installation.id)
        : null;
      if (!octokit) return;

      const priorityEmoji: Record<string, string> = {
        critical: "🔴",
        high: "🟠",
        medium: "🟡",
        low: "🟢",
      };

      const appliedLabels = [...triage.labels, `priority:${triage.priority}`];
      const body = `## Dispatch AI Triage\n\n**Summary:** ${triage.summary}\n\n**Priority:** ${priorityEmoji[triage.priority] ?? "⚪"} ${triage.priority.charAt(0).toUpperCase() + triage.priority.slice(1)}\n**Category:** ${triage.category}\n**Labels applied:** ${appliedLabels.map((l) => `\`${l}\``).join(", ")}\n\n**Recommended action:** ${triage.action}\n\n---\n*Generated by [Dispatch](https://github.com/apps/dispatch)*`;

      await postIssueComment(octokit, owner, repoName, issue.number, body);
    });

    await step.run("save-to-db", async () => {
      await db.insert(triageResults).values({
        repoFullName: repo.full_name,
        issueNumber: issue.number,
        labels: [...triage.labels, `priority:${triage.priority}`],
        priority: triage.priority,
      });
    });

    return {
      success: true,
      repoFullName: repo.full_name,
      issueNumber: issue.number,
      triage,
    };
  }
);
